# Generated by Django 3.0.4 on 2020-03-17 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=200)),
                ('last_name', models.TextField(max_length=200)),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
            ],
            options={
                'verbose_name_plural': 'Actor',
                'db_table': 'Actor',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=500)),
                ('address2', models.TextField(max_length=500, null=True)),
                ('district', models.TextField(max_length=100)),
                ('postal_code', models.IntegerField(max_length=6)),
                ('phone', models.IntegerField(max_length=15)),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last updated address')),
            ],
            options={
                'verbose_name_plural': 'Address',
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last updated date')),
            ],
            options={
                'verbose_name_plural': 'category',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(max_length=200)),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last updated date country')),
            ],
            options={
                'verbose_name_plural': 'Country',
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=200)),
                ('last_name', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('activebool', models.IntegerField(choices=[(0, 'Deactivate'), (1, 'Activate')], default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date Customer')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
                ('active', models.IntegerField(choices=[(0, 'Deactivate'), (1, 'Active'), (2, 'Pending'), (3, 'Rejected')], default=0)),
                ('address', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='address_customer', to='film.Address', verbose_name='Address')),
            ],
            options={
                'verbose_name_plural': 'Customer',
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=200)),
                ('release_year', models.IntegerField()),
                ('rental_duration', models.IntegerField()),
                ('rental_rate', models.FloatField()),
                ('length', models.IntegerField()),
                ('replacement_cost', models.FloatField()),
                ('rating', models.TextField(max_length=200)),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last updated date')),
                ('special_features', models.TextField(max_length=200)),
                ('fulltext', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Film',
                'db_table': 'Film',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='LAst updated date')),
                ('film', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='film_inv', to='film.Film', verbose_name='Film')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
                'db_table': 'Inventory',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last updated date')),
            ],
            options={
                'verbose_name_plural': 'Language',
                'db_table': 'Language',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last updated store date')),
                ('address', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='address_store', to='film.Address', verbose_name='Address')),
            ],
            options={
                'verbose_name_plural': 'Store',
                'db_table': 'Store',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=200)),
                ('last_name', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.IntegerField(choices=[(0, 'Deactivate'), (1, 'Active'), (2, 'Pending'), (3, 'Rejected')], default=0)),
                ('username', models.TextField(max_length=200)),
                ('password', models.TextField(max_length=30)),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last updated date')),
                ('address', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='address_staff', to='film.Address', verbose_name='Address')),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store_staff', to='film.Store', verbose_name='Store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'StaffProfile',
                'db_table': 'StaffProfile',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField()),
                ('return_date', models.DateField()),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last updated date')),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_rental', to='film.Customer', verbose_name='Customer')),
                ('inventory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inv_rental', to='film.Inventory', verbose_name='Inventory')),
                ('staff', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_rental', to='film.StaffProfile', verbose_name='StaffProfile')),
            ],
            options={
                'verbose_name_plural': 'Rental',
                'db_table': 'Rental',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=20)),
                ('payment_date', models.DateTimeField(auto_now=True, verbose_name='Last payment date')),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_payment', to='film.Customer', verbose_name='Customer')),
                ('rental', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rental_payment', to='film.Rental', verbose_name='Rental')),
                ('staff', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_payment', to='film.StaffProfile', verbose_name='StaffProfile')),
            ],
            options={
                'verbose_name_plural': 'Payment',
                'db_table': 'Payment',
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store_inv', to='film.Store', verbose_name='Store'),
        ),
        migrations.CreateModel(
            name='FilmCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last updated date')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_film', to='film.Category', verbose_name='Category')),
                ('film', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='film', to='film.Film', verbose_name='Film')),
            ],
            options={
                'verbose_name_plural': 'FilmCategory',
                'db_table': 'FilmCategory',
            },
        ),
        migrations.CreateModel(
            name='FilmActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last updated date')),
                ('actor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actor_film', to='film.Actor', verbose_name='Actor')),
                ('film', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='film_film', to='film.Film', verbose_name='Film')),
            ],
            options={
                'verbose_name_plural': 'FilmActor',
                'db_table': 'FilmActor',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='language_film', to='film.Language', verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='customer',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='film.Store', verbose_name='Store'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(max_length=200)),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last updated date city ')),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_city', to='film.Country', verbose_name='Country')),
            ],
            options={
                'verbose_name_plural': 'City',
                'db_table': 'City',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='city_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city_address', to='film.City', verbose_name='City'),
        ),
    ]
