# Generated by Django 3.0.4 on 2020-03-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_auto_20200317_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
