# Generated by Django 3.0.4 on 2020-03-18 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_auto_20200318_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmactor',
            name='actor',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
