# Generated by Django 3.0.4 on 2020-03-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_auto_20200318_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=200)),
                ('last_name', models.TextField(max_length=200)),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last update date')),
            ],
            options={
                'verbose_name_plural': 'Actor',
                'db_table': 'Actor',
            },
        ),
    ]
