# Generated by Django 3.0.4 on 2020-03-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0009_auto_20200318_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='last_update',
            field=models.DateField(auto_now=True, verbose_name='Last updated date'),
        ),
    ]
