# Generated by Django 3.0.4 on 2020-03-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0011_auto_20200318_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(error_messages={'unique': 'This mail is already exist.'}, max_length=200),
        ),
    ]
