# Generated by Django 3.0.4 on 2020-03-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0012_auto_20200318_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
