# Generated by Django 3.0.4 on 2020-03-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0013_auto_20200318_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
