# Generated by Django 3.0.4 on 2020-03-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0016_auto_20200319_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
